import 'package:flutter/material.dart';

@immutable
class CustomColorsExtension extends ThemeExtension<CustomColorsExtension> {
  final Color twColor007AFF,
      twColor00FFFFFF,
      twColor091E42,
      twColor091E4226,
      twColor118CE4,
      twColor141414,
      twColor1A1C1F,
      twColor1D252D,
      twColor2098EE,
      twColor22203D,
      twColor22A45D,
      twColor34383E,
      twColor423A67,
      twColor455560,
      twColor4B4776,
      twColor4c4776,
      twColor5db364,
      twColor5DB364,
      twColor676F7C,
      twColor67BF76,
      twColor6E9fbb,
      twColor761d2d,
      twColor761D2D,
      twColor818B9B,
      twColor8780F2,
      twColor8a20f4,
      twColor8f73f2,
      twColor9747ff,
      twColor9AA2AF,
      twColorA8A9CF,
      twColorB347F5,
      twColorB3B9C3,
      twCOlorbac9AA2AF,
      twColorbac9AA2AF,
      twColorbB3B9C3,
      twColorBlack,
      twColorC0C2E8,
      twColorD9A51F,
      twColorD9DCE1,
      twColordadada,
      twColorDB1753,
      twColorE0DEE7,
      twColorE4F1F8,
      twColorede8fe,
      twColorEE750033,
      twColorF0F0F0,
      twColorf0fff5,
      twColorF0FFF5,
      twColorF2F3F5,
      twColorF47B20,
      twColorF5F2FF,
      twColorF8F6FF,
      twColorfdf1e5,
      twColorff4136,
      twColorFF4136,
      twColorFF6D01,
      twColorFFF1CC,
      twColorFFF1E4,
      twColorFFF2F1,
      twColorfff2f1,
      twColorSuccessGreenText,
      twDisableColor,
      twSecondaryColor,
      twWhite,
      twColorE71757,
      twScaffoldBgColor,
      twColorFFF1E7,
      twColorFF7312,
      twColorFFEAF2,
      twColorFF2E7D,
      twColorEBFCF5,
      twColor33E39D,
      twColorTrackColor,
      twColorF09D98,
      twColor312E52,
      twPrimaryColorOne,
      twPrimaryColorTwo,
      twColorD6D1ED,
      twColor6B47F5,
      twColorF8F9FB,
      primaryColor,
      twBlack,
      twWhiteColor,
      twLightPrimaryWhite,
      twGrey,
      twLightPrimary,
      twDark,
      twDarkgreyWhite,
      twLightRed,
      twPinTextColor,
      twGreyWhite,
      twDisableWhite,
      twGreyDisable,
      twPrimaryTwoGrey,
      twPrimaryTwoSecondary,
      twWhitePrimaryTwo,
      twPrimaryTwoWhite,
      twSecondaryWhite,
      twPrimaryWhite,
      twWhiteBlackColor,
      twDangerColor,
      twColorEACAB3,
      twWhiteDarkColor,
      twDarkWhiteColor,
      twBlackWhiteColor;
  final List<Color> linearGradientEliteTag;
  const CustomColorsExtension(
      {required this.primaryColor,
      required this.twColor007AFF,
      required this.twColor00FFFFFF,
      required this.twColor091E42,
      required this.twColor091E4226,
      required this.twColor118CE4,
      required this.twColor141414,
      required this.twColor1A1C1F,
      required this.twColor1D252D,
      required this.twColor2098EE,
      required this.twColor22203D,
      required this.twColor22A45D,
      required this.twColor34383E,
      required this.twColor423A67,
      required this.twColor455560,
      required this.twColor4B4776,
      required this.twColor4c4776,
      required this.twColor5db364,
      required this.twColor5DB364,
      required this.twColor676F7C,
      required this.twColor67BF76,
      required this.twColor6E9fbb,
      required this.twColor761d2d,
      required this.twColor761D2D,
      required this.twColor818B9B,
      required this.twColor8780F2,
      required this.twColor8a20f4,
      required this.twColor8f73f2,
      required this.twColor9747ff,
      required this.twColor9AA2AF,
      required this.twColorA8A9CF,
      required this.twColorB347F5,
      required this.twColorB3B9C3,
      required this.twCOlorbac9AA2AF,
      required this.twColorbac9AA2AF,
      required this.twColorbB3B9C3,
      required this.twColorBlack,
      required this.twColorC0C2E8,
      required this.twColorD9A51F,
      required this.twColorD9DCE1,
      required this.twColordadada,
      required this.twColorDB1753,
      required this.twColorE0DEE7,
      required this.twColorE4F1F8,
      required this.twColorede8fe,
      required this.twColorEE750033,
      required this.twColorF0F0F0,
      required this.twColorf0fff5,
      required this.twColorF0FFF5,
      required this.twColorF2F3F5,
      required this.twColorF47B20,
      required this.twColorF5F2FF,
      required this.twColorF8F6FF,
      required this.twColorfdf1e5,
      required this.twColorff4136,
      required this.twColorFF4136,
      required this.twColorFF6D01,
      required this.twColorFFF1CC,
      required this.twColorFFF1E4,
      required this.twColorFFF2F1,
      required this.twColorfff2f1,
      required this.twColorSuccessGreenText,
      required this.twDisableColor,
      required this.twSecondaryColor,
      required this.twWhite,
      required this.twColorE71757,
      required this.twScaffoldBgColor,
      required this.twColorFFF1E7,
      required this.twColorFF7312,
      required this.twColorFFEAF2,
      required this.twColorFF2E7D,
      required this.twColorEBFCF5,
      required this.twColor33E39D,
      required this.twColorTrackColor,
      required this.twColorF09D98,
      required this.twColor312E52,
      required this.twPrimaryColorOne,
      required this.twPrimaryColorTwo,
      required this.twColorD6D1ED,
      required this.twColor6B47F5,
      required this.twColorF8F9FB,
      required this.twBlack,
      required this.twWhiteColor,
      required this.twLightPrimaryWhite,
      required this.linearGradientEliteTag,
      required this.twGrey,
      required this.twLightPrimary,
      required this.twDark,
      required this.twDarkgreyWhite,
      required this.twLightRed,
      required this.twPinTextColor,
      required this.twGreyWhite,
      required this.twDisableWhite,
      required this.twGreyDisable,
      required this.twPrimaryTwoGrey,
      required this.twPrimaryTwoSecondary,
      required this.twWhitePrimaryTwo,
      required this.twPrimaryTwoWhite,
      required this.twSecondaryWhite,
      required this.twPrimaryWhite,
      required this.twWhiteBlackColor,
      required this.twDangerColor,
      required this.twColorEACAB3,
      required this.twWhiteDarkColor,
      required this.twDarkWhiteColor,
      required this.twBlackWhiteColor});

  @override
  ThemeExtension<CustomColorsExtension> copyWith(
      {Color? twColor007AFF,
      Color? twColor00FFFFFF,
      Color? twColor091E42,
      Color? twColor091E4226,
      Color? twColor118CE4,
      Color? twColor141414,
      Color? twColor1A1C1F,
      Color? twColor1D252D,
      Color? twColor2098EE,
      Color? twColor22203D,
      Color? twColor22A45D,
      Color? twColor34383E,
      Color? twColor423A67,
      Color? twColor455560,
      Color? twColor4B4776,
      Color? twColor4c4776,
      Color? twColor5db364,
      Color? twColor5DB364,
      Color? twColor676F7C,
      Color? twColor67BF76,
      Color? twColor6E9fbb,
      Color? twColor761d2d,
      Color? twColor761D2D,
      Color? twColor818B9B,
      Color? twColor8780F2,
      Color? twColor8a20f4,
      Color? twColor8f73f2,
      Color? twColor9747ff,
      Color? twColor9AA2AF,
      Color? twColorA8A9CF,
      Color? twColorB347F5,
      Color? twColorB3B9C3,
      Color? twCOlorbac9AA2AF,
      Color? twColorbac9AA2AF,
      Color? twColorbB3B9C3,
      Color? twColorBlack,
      Color? twColorC0C2E8,
      Color? twColorD9A51F,
      Color? twColorD9DCE1,
      Color? twColordadada,
      Color? twColorDB1753,
      Color? twColorE0DEE7,
      Color? twColorE4F1F8,
      Color? twColorede8fe,
      Color? twColorEE750033,
      Color? twColorF0F0F0,
      Color? twColorf0fff5,
      Color? twColorF0FFF5,
      Color? twColorF2F3F5,
      Color? twColorF47B20,
      Color? twColorF5F2FF,
      Color? twColorF8F6FF,
      Color? twColorfdf1e5,
      Color? twColorff4136,
      Color? twColorFF4136,
      Color? twColorFF6D01,
      Color? twColorFFF1CC,
      Color? twColorFFF1E4,
      Color? twColorFFF2F1,
      Color? twColorfff2f1,
      Color? twColorSuccessGreenText,
      Color? twDisableColor,
      Color? twSecondaryColor,
      Color? twWhite,
      Color? twColorE71757,
      Color? twScaffoldBgColor,
      Color? twColorFFF1E7,
      Color? twColorFF7312,
      Color? twColorFFEAF2,
      Color? twColorFF2E7D,
      Color? twColorEBFCF5,
      Color? twColor33E39D,
      Color? twColorTrackColor,
      Color? twColorF09D98,
      Color? twColor312E52,
      Color? twPrimaryColorOne,
      Color? twPrimaryColorTwo,
      Color? twColorD6D1ED,
      Color? twColor6B47F5,
      Color? twColorF8F9FB,
      Color? twLightPrimaryWhite,
      List<Color>? linearGradientEliteTag,
      Color? twGrey,
      Color? twLightPrimary,
      Color? twDark,
      Color? twDarkgreyWhite,
      Color? twLightRed,
      Color? twPinTextColor,
      Color? twGreyWhite,
      Color? twDisableWhite,
      Color? twGreyDisable,
      Color? twPrimaryTwoGrey,
      Color? twPrimaryTwoSecondary,
      Color? twWhitePrimaryTwo,
      Color? twPrimaryTwoWhite,
      Color? twSecondaryWhite,
      Color? twPrimaryWhite,
      Color? twWhiteBlackColor,
      Color? twDangerColor,
      Color? twColorEACAB3,
      Color? twWhiteDarkColor,
      Color? twDarkWhiteColor,
      Color? twBlackWhiteColor,
      Color? primaryColor,
      Color? twBlack,
      Color? twWhiteColor}) {
    return CustomColorsExtension(
      twColor007AFF: twColor007AFF ?? this.twColor007AFF,
      twColor00FFFFFF: twColor00FFFFFF ?? this.twColor00FFFFFF,
      twColor091E42: twColor091E42 ?? this.twColor091E42,
      twColor091E4226: twColor091E4226 ?? this.twColor091E4226,
      twColor118CE4: twColor118CE4 ?? this.twColor118CE4,
      twColor141414: twColor141414 ?? this.twColor141414,
      twColor1A1C1F: twColor1A1C1F ?? this.twColor1A1C1F,
      twColor1D252D: twColor1D252D ?? this.twColor1D252D,
      twColor2098EE: twColor2098EE ?? this.twColor2098EE,
      twColor22203D: twColor22203D ?? this.twColor22203D,
      twColor22A45D: twColor22A45D ?? this.twColor22A45D,
      twColor34383E: twColor34383E ?? this.twColor34383E,
      twColor423A67: twColor423A67 ?? this.twColor423A67,
      twColor455560: twColor455560 ?? this.twColor455560,
      twColor4B4776: twColor4B4776 ?? this.twColor4B4776,
      twColor4c4776: twColor4c4776 ?? this.twColor4c4776,
      twColor5db364: twColor5db364 ?? this.twColor5db364,
      twColor5DB364: twColor5DB364 ?? this.twColor5DB364,
      twColor676F7C: twColor676F7C ?? this.twColor676F7C,
      twColor67BF76: twColor67BF76 ?? this.twColor67BF76,
      twColor6E9fbb: twColor6E9fbb ?? this.twColor6E9fbb,
      twColor761d2d: twColor761d2d ?? this.twColor761d2d,
      twColor761D2D: twColor761D2D ?? this.twColor761D2D,
      twColor818B9B: twColor818B9B ?? this.twColor818B9B,
      twColor8780F2: twColor8780F2 ?? this.twColor8780F2,
      twColor8a20f4: twColor8a20f4 ?? this.twColor8a20f4,
      twColor8f73f2: twColor8f73f2 ?? this.twColor8f73f2,
      twColor9747ff: twColor9747ff ?? this.twColor9747ff,
      twColor9AA2AF: twColor9AA2AF ?? this.twColor9AA2AF,
      twColorA8A9CF: twColorA8A9CF ?? this.twColorA8A9CF,
      twColorB347F5: twColorB347F5 ?? this.twColorB347F5,
      twColorB3B9C3: twColorB3B9C3 ?? this.twColorB3B9C3,
      twCOlorbac9AA2AF: twCOlorbac9AA2AF ?? this.twCOlorbac9AA2AF,
      twColorbac9AA2AF: twColorbac9AA2AF ?? this.twColorbac9AA2AF,
      twColorbB3B9C3: twColorbB3B9C3 ?? this.twColorbB3B9C3,
      twColorBlack: twColorBlack ?? this.twColorBlack,
      twColorC0C2E8: twColorC0C2E8 ?? this.twColorC0C2E8,
      twColorD9A51F: twColorD9A51F ?? this.twColorD9A51F,
      twColorD9DCE1: twColorD9DCE1 ?? this.twColorD9DCE1,
      twColordadada: twColordadada ?? this.twColordadada,
      twColorDB1753: twColorDB1753 ?? this.twColorDB1753,
      twColorE0DEE7: twColorE0DEE7 ?? this.twColorE0DEE7,
      twColorE4F1F8: twColorE4F1F8 ?? this.twColorE4F1F8,
      twColorede8fe: twColorede8fe ?? this.twColorede8fe,
      twColorEE750033: twColorEE750033 ?? this.twColorEE750033,
      twColorF0F0F0: twColorF0F0F0 ?? this.twColorF0F0F0,
      twColorf0fff5: twColorf0fff5 ?? this.twColorf0fff5,
      twColorF0FFF5: twColorF0FFF5 ?? this.twColorF0FFF5,
      twColorF2F3F5: twColorF2F3F5 ?? this.twColorF2F3F5,
      twColorF47B20: twColorF47B20 ?? this.twColorF47B20,
      twColorF5F2FF: twColorF5F2FF ?? this.twColorF5F2FF,
      twColorF8F6FF: twColorF8F6FF ?? this.twColorF8F6FF,
      twColorfdf1e5: twColorfdf1e5 ?? this.twColorfdf1e5,
      twColorff4136: twColorff4136 ?? this.twColorff4136,
      twColorFF4136: twColorFF4136 ?? this.twColorFF4136,
      twColorFF6D01: twColorFF6D01 ?? this.twColorFF6D01,
      twColorFFF1CC: twColorFFF1CC ?? this.twColorFFF1CC,
      twColorFFF1E4: twColorFFF1E4 ?? this.twColorFFF1E4,
      twColorFFF2F1: twColorFFF2F1 ?? this.twColorFFF2F1,
      twColorfff2f1: twColorfff2f1 ?? this.twColorfff2f1,
      twColorSuccessGreenText:
          twColorSuccessGreenText ?? this.twColorSuccessGreenText,
      twDisableColor: twDisableColor ?? this.twDisableColor,
      twSecondaryColor: twSecondaryColor ?? this.twSecondaryColor,
      twWhite: twWhite ?? this.twWhite,
      twColorE71757: twColorE71757 ?? this.twColorE71757,
      twScaffoldBgColor: twScaffoldBgColor ?? this.twScaffoldBgColor,
      twColorFFF1E7: twColorFFF1E7 ?? this.twColorFFF1E7,
      twColorFF7312: twColorFF7312 ?? this.twColorFF7312,
      twColorFFEAF2: twColorFFEAF2 ?? this.twColorFFEAF2,
      twColorFF2E7D: twColorFF2E7D ?? this.twColorFF2E7D,
      twColorEBFCF5: twColorEBFCF5 ?? this.twColorEBFCF5,
      twColor33E39D: twColor33E39D ?? this.twColor33E39D,
      twColorTrackColor: twColorTrackColor ?? this.twColorTrackColor,
      twColorF09D98: twColorF09D98 ?? this.twColorF09D98,
      twColor312E52: twColor312E52 ?? this.twColor312E52,
      twPrimaryColorOne: twPrimaryColorOne ?? this.twPrimaryColorOne,
      twPrimaryColorTwo: twPrimaryColorTwo ?? this.twPrimaryColorTwo,
      twColorD6D1ED: twColorD6D1ED ?? this.twColorD6D1ED,
      twColor6B47F5: twColor6B47F5 ?? this.twColor6B47F5,
      twColorF8F9FB: twColorF8F9FB ?? this.twColorF8F9FB,
      twLightPrimaryWhite: twLightPrimaryWhite ?? this.twLightPrimaryWhite,
      linearGradientEliteTag:
          linearGradientEliteTag ?? this.linearGradientEliteTag,
      primaryColor: primaryColor ?? this.primaryColor,
      twBlack: twBlack ?? this.twBlack,
      twBlackWhiteColor: twBlackWhiteColor ?? this.twBlackWhiteColor,
      twColorEACAB3: twColorEACAB3 ?? this.twColorEACAB3,
      twDangerColor: twDangerColor ?? this.twDangerColor,
      twDark: twDark ?? this.twDark,
      twDarkWhiteColor: twDarkWhiteColor ?? this.twDarkWhiteColor,
      twDarkgreyWhite: twDarkgreyWhite ?? this.twDarkgreyWhite,
      twDisableWhite: twDisableWhite ?? this.twDisableWhite,
      twGrey: twGrey ?? this.twGrey,
      twGreyDisable: twGreyDisable ?? this.twGreyDisable,
      twGreyWhite: twGreyWhite ?? this.twGreyWhite,
      twLightPrimary: twLightPrimary ?? this.twLightPrimary,
      twLightRed: twLightRed ?? this.twLightRed,
      twPinTextColor: twPinTextColor ?? this.twPinTextColor,
      twPrimaryTwoGrey: twPrimaryTwoGrey ?? this.twPrimaryTwoGrey,
      twPrimaryTwoSecondary:
          twPrimaryTwoSecondary ?? this.twPrimaryTwoSecondary,
      twPrimaryTwoWhite: twPrimaryTwoWhite ?? this.twPrimaryTwoWhite,
      twPrimaryWhite: twPrimaryWhite ?? this.twPrimaryWhite,
      twSecondaryWhite: twSecondaryWhite ?? this.twSecondaryWhite,
      twWhiteBlackColor: twWhiteBlackColor ?? this.twWhiteBlackColor,
      twWhiteColor: twWhiteColor ?? this.twWhiteColor,
      twWhiteDarkColor: twWhiteDarkColor ?? this.twWhiteDarkColor,
      twWhitePrimaryTwo: twWhitePrimaryTwo ?? this.twWhitePrimaryTwo,
    );
  }

  @override
  ThemeExtension<CustomColorsExtension> lerp(
      covariant ThemeExtension<CustomColorsExtension>? other, double t) {
    if (other is! CustomColorsExtension) {
      return this;
    }
    return CustomColorsExtension(
      twColor007AFF: Color.lerp(twColor007AFF, other.twColor007AFF, t)!,
      twColor00FFFFFF: Color.lerp(twColor00FFFFFF, other.twColor00FFFFFF, t)!,
      twColor091E42: Color.lerp(twColor091E42, other.twColor091E42, t)!,
      twColor091E4226: Color.lerp(twColor091E4226, other.twColor091E4226, t)!,
      twColor118CE4: Color.lerp(twColor118CE4, other.twColor118CE4, t)!,
      twColor141414: Color.lerp(twColor141414, other.twColor141414, t)!,
      twColor1A1C1F: Color.lerp(twColor1A1C1F, other.twColor1A1C1F, t)!,
      twColor1D252D: Color.lerp(twColor1D252D, other.twColor1D252D, t)!,
      twColor2098EE: Color.lerp(twColor2098EE, other.twColor2098EE, t)!,
      twColor22203D: Color.lerp(twColor22203D, other.twColor22203D, t)!,
      twColor22A45D: Color.lerp(twColor22A45D, other.twColor22A45D, t)!,
      twColor34383E: Color.lerp(twColor34383E, other.twColor34383E, t)!,
      twColor423A67: Color.lerp(twColor423A67, other.twColor423A67, t)!,
      twColor455560: Color.lerp(twColor455560, other.twColor455560, t)!,
      twColor4B4776: Color.lerp(twColor4B4776, other.twColor4B4776, t)!,
      twColor4c4776: Color.lerp(twColor4c4776, other.twColor4c4776, t)!,
      twColor5db364: Color.lerp(twColor5db364, other.twColor5db364, t)!,
      twColor5DB364: Color.lerp(twColor5DB364, other.twColor5DB364, t)!,
      twColor676F7C: Color.lerp(twColor676F7C, other.twColor676F7C, t)!,
      twColor67BF76: Color.lerp(twColor67BF76, other.twColor67BF76, t)!,
      twColor6E9fbb: Color.lerp(twColor6E9fbb, other.twColor6E9fbb, t)!,
      twColor761d2d: Color.lerp(twColor761d2d, other.twColor761d2d, t)!,
      twColor761D2D: Color.lerp(twColor761D2D, other.twColor761D2D, t)!,
      twColor818B9B: Color.lerp(twColor818B9B, other.twColor818B9B, t)!,
      twColor8780F2: Color.lerp(twColor8780F2, other.twColor8780F2, t)!,
      twColor8a20f4: Color.lerp(twColor8a20f4, other.twColor8a20f4, t)!,
      twColor8f73f2: Color.lerp(twColor8f73f2, other.twColor8f73f2, t)!,
      twColor9747ff: Color.lerp(twColor9747ff, other.twColor9747ff, t)!,
      twColor9AA2AF: Color.lerp(twColor9AA2AF, other.twColor9AA2AF, t)!,
      twColorA8A9CF: Color.lerp(twColorA8A9CF, other.twColorA8A9CF, t)!,
      twColorB347F5: Color.lerp(twColorB347F5, other.twColorB347F5, t)!,
      twColorB3B9C3: Color.lerp(twColorB3B9C3, other.twColorB3B9C3, t)!,
      twCOlorbac9AA2AF:
          Color.lerp(twCOlorbac9AA2AF, other.twCOlorbac9AA2AF, t)!,
      twColorbac9AA2AF:
          Color.lerp(twColorbac9AA2AF, other.twColorbac9AA2AF, t)!,
      twColorbB3B9C3: Color.lerp(twColorbB3B9C3, other.twColorbB3B9C3, t)!,
      twColorBlack: Color.lerp(twColorBlack, other.twColorBlack, t)!,
      twColorC0C2E8: Color.lerp(twColorC0C2E8, other.twColorC0C2E8, t)!,
      twColorD9A51F: Color.lerp(twColorD9A51F, other.twColorD9A51F, t)!,
      twColorD9DCE1: Color.lerp(twColorD9DCE1, other.twColorD9DCE1, t)!,
      twColordadada: Color.lerp(twColordadada, other.twColordadada, t)!,
      twColorDB1753: Color.lerp(twColorDB1753, other.twColorDB1753, t)!,
      twColorE0DEE7: Color.lerp(twColorE0DEE7, other.twColorE0DEE7, t)!,
      twColorE4F1F8: Color.lerp(twColorE4F1F8, other.twColorE4F1F8, t)!,
      twColorede8fe: Color.lerp(twColorede8fe, other.twColorede8fe, t)!,
      twColorEE750033: Color.lerp(twColorEE750033, other.twColorEE750033, t)!,
      twColorF0F0F0: Color.lerp(twColorF0F0F0, other.twColorF0F0F0, t)!,
      twColorf0fff5: Color.lerp(twColorf0fff5, other.twColorf0fff5, t)!,
      twColorF0FFF5: Color.lerp(twColorF0FFF5, other.twColorF0FFF5, t)!,
      twColorF2F3F5: Color.lerp(twColorF2F3F5, other.twColorF2F3F5, t)!,
      twColorF47B20: Color.lerp(twColorF47B20, other.twColorF47B20, t)!,
      twColorF5F2FF: Color.lerp(twColorF5F2FF, other.twColorF5F2FF, t)!,
      twColorF8F6FF: Color.lerp(twColorF8F6FF, other.twColorF8F6FF, t)!,
      twColorfdf1e5: Color.lerp(twColorfdf1e5, other.twColorfdf1e5, t)!,
      twColorff4136: Color.lerp(twColorff4136, other.twColorff4136, t)!,
      twColorFF4136: Color.lerp(twColorFF4136, other.twColorFF4136, t)!,
      twColorFF6D01: Color.lerp(twColorFF6D01, other.twColorFF6D01, t)!,
      twColorFFF1CC: Color.lerp(twColorFFF1CC, other.twColorFFF1CC, t)!,
      twColorFFF1E4: Color.lerp(twColorFFF1E4, other.twColorFFF1E4, t)!,
      twColorFFF2F1: Color.lerp(twColorFFF2F1, other.twColorFFF2F1, t)!,
      twColorfff2f1: Color.lerp(twColorfff2f1, other.twColorfff2f1, t)!,
      twColorSuccessGreenText: Color.lerp(
          twColorSuccessGreenText, other.twColorSuccessGreenText, t)!,
      twDisableColor: Color.lerp(twDisableColor, other.twDisableColor, t)!,
      twSecondaryColor:
          Color.lerp(twSecondaryColor, other.twSecondaryColor, t)!,
      twWhite: Color.lerp(twSecondaryColor, other.twSecondaryColor, t)!,
      twColorE71757: Color.lerp(twColorE71757, other.twColorE71757, t)!,
      twScaffoldBgColor:
          Color.lerp(twScaffoldBgColor, other.twScaffoldBgColor, t)!,
      twColorFFF1E7: Color.lerp(twColorFFF1E7, other.twColorFFF1E7, t)!,
      twColorFF7312: Color.lerp(twColorFF7312, other.twColorFF7312, t)!,
      twColorFFEAF2: Color.lerp(twColorFFEAF2, other.twColorFFEAF2, t)!,
      twColorFF2E7D: Color.lerp(twColorFF2E7D, other.twColorFF2E7D, t)!,
      twColorEBFCF5: Color.lerp(twColorEBFCF5, other.twColorEBFCF5, t)!,
      twColor33E39D: Color.lerp(twColor33E39D, other.twColor33E39D, t)!,
      twColorTrackColor:
          Color.lerp(twColorTrackColor, other.twColorTrackColor, t)!,
      twColorF09D98: Color.lerp(twColorF09D98, other.twColorF09D98, t)!,
      twColor312E52: Color.lerp(twColor312E52, other.twColor312E52, t)!,
      twPrimaryColorOne:
          Color.lerp(twPrimaryColorOne, other.twPrimaryColorOne, t)!,
      twPrimaryColorTwo:
          Color.lerp(twPrimaryColorTwo, other.twPrimaryColorTwo, t)!,
      twColorD6D1ED: Color.lerp(twColorD6D1ED, other.twColorD6D1ED, t)!,
      twColor6B47F5: Color.lerp(twColor6B47F5, other.twColor6B47F5, t)!,
      twColorF8F9FB: Color.lerp(twColorF8F9FB, other.twColorF8F9FB, t)!,
      linearGradientEliteTag: linearGradientEliteTag
          .asMap()
          .map((key, value) => MapEntry(
              key,
              Color.lerp(
                  value, other.linearGradientEliteTag.elementAt(key), t)!))
          .values
          .toList(),
      primaryColor: Color.lerp(primaryColor, other.primaryColor, t)!,
      twBlack: Color.lerp(twBlack, other.twBlack, t)!,
      twBlackWhiteColor:
          Color.lerp(twBlackWhiteColor, other.twBlackWhiteColor, t)!,
      twColorEACAB3: Color.lerp(twColorEACAB3, other.twColorEACAB3, t)!,
      twDangerColor: Color.lerp(twDangerColor, other.twDangerColor, t)!,
      twDark: Color.lerp(twDark, other.twDark, t)!,
      twDarkWhiteColor:
          Color.lerp(twDarkWhiteColor, other.twDarkWhiteColor, t)!,
      twDarkgreyWhite: Color.lerp(twDarkgreyWhite, other.twDarkgreyWhite, t)!,
      twDisableWhite: Color.lerp(twDisableWhite, other.twDisableWhite, t)!,
      twGrey: Color.lerp(twGrey, other.twGrey, t)!,
      twGreyDisable: Color.lerp(twGreyDisable, other.twGreyDisable, t)!,
      twGreyWhite: Color.lerp(twGreyWhite, other.twGreyWhite, t)!,
      twLightPrimary: Color.lerp(twLightPrimary, other.twLightPrimary, t)!,
      twLightPrimaryWhite:
          Color.lerp(twLightPrimaryWhite, other.twLightPrimaryWhite, t)!,
      twLightRed: Color.lerp(twLightRed, other.twLightRed, t)!,
      twPinTextColor: Color.lerp(twPinTextColor, other.twPinTextColor, t)!,
      twPrimaryTwoGrey:
          Color.lerp(twPrimaryTwoGrey, other.twPrimaryTwoGrey, t)!,
      twPrimaryTwoSecondary:
          Color.lerp(twPrimaryTwoSecondary, other.twPrimaryTwoSecondary, t)!,
      twPrimaryTwoWhite:
          Color.lerp(twPrimaryTwoWhite, other.twPrimaryTwoWhite, t)!,
      twPrimaryWhite: Color.lerp(twPrimaryWhite, other.twPrimaryWhite, t)!,
      twSecondaryWhite:
          Color.lerp(twSecondaryWhite, other.twSecondaryWhite, t)!,
      twWhiteBlackColor:
          Color.lerp(twWhiteBlackColor, other.twWhiteBlackColor, t)!,
      twWhiteColor: Color.lerp(twWhiteColor, other.twWhiteColor, t)!,
      twWhiteDarkColor:
          Color.lerp(twWhiteDarkColor, other.twWhiteDarkColor, t)!,
      twWhitePrimaryTwo:
          Color.lerp(twWhitePrimaryTwo, other.twWhitePrimaryTwo, t)!,
    );
  }
}
